services:
  backend:
    image: app_tracker_back_dev:python-3.12-alpine
    container_name: app_tracker_backend_dev
    build:
      target: development
    volumes:
      - ./backend/app:/code/app
    ports:
      - 8000:8000

  frontend:
    image: app_tracker_front_dev:node-23-alpine3.19
    container_name: app_tracker_frontend_dev
    volumes:
      - ./frontend:/code/
    build:
      target: development
    ports:
      - 5173:5173
    environment:
      - NODE_ENV=development

  pgadmin:
    image: dpage/pgadmin4:8.13.0
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 1654:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - default
    depends_on:
      - postgres

volumes:
  pgadmin-data:
