ARG PYTHON_VERSION=3.12
ARG UV_VERSION=0.8.13

FROM python:${PYTHON_VERSION}

ARG NODE_VERSION=23

WORKDIR /code

ENV PATH="/code/backend/.venv/bin:$PATH"


# Install additional software
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git nano man-db


COPY .devcontainer/set_up_zsh.sh /tmp/set_up_zsh.sh
COPY .devcontainer/.spaceshiprc.zsh /tmp/.spaceshiprc.zsh
RUN sh /tmp/set_up_zsh.sh

# Install uv (pinned)
COPY --from=ghcr.io/astral-sh/uv:${UV_VERSION} /uv /uvx /bin/

# Install node
RUN curl -fsSL https://deb.nodesource.com/setup_${NODE_VERSION}.x -o nodesource_setup.sh && \
    bash nodesource_setup.sh && \
    apt-get install -y nodejs
