services:

  backend:
    container_name: application_tacker_backend
    build: ./backend
    env_file:
      - .env
    ports:
      - 8000:80
  
  frontend:
    container_name: application_tracker_frontend
    build: ./frontend
    ports:
      - 3000:3000
  
  postgres:
    image: postgres:17-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5433:${POSTGRES_PORT}
    
volumes:
  postgres-data:
    name: postgres_data_volume