FROM python:${PYTHON_VERSION}

WORKDIR /code

    # create .venv in project directory
ENV POETRY_VIRTUALENVS_IN_PROJECT=1 \
    # Ensure pipx is available in the PATH
    PATH="/root/.local/bin:$PATH"

# Install git
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git

# Install system dependencies and pipx
RUN python3 -m pip install --user pipx && \
    python3 -m pipx ensurepath && \
    # Install Poetry using pipx
    pipx install poetry==${POETRY_VERSION}

# Install node
RUN curl -fsSL https://deb.nodesource.com/setup_23.x -o nodesource_setup.sh && \
    bash nodesource_setup.sh && \
    apt-get install -y nodejs

RUN apt-get install -y nano man-db

COPY ./.devcontainer/set_up_zsh.sh /tmp/set_up_zsh.sh

COPY ./.devcontainer/.spaceshiprc.zsh /tmp/.spaceshiprc.zsh

RUN sh /tmp/set_up_zsh.sh
