services:
  backend:
    build:
      context: ./backend
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - default

  frontend:
    build:
      context: ./frontend
    env_file:
      - .env
    networks:
      - default

  postgres:
    image: postgres:17-alpine
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5434:${POSTGRES_PORT}
    networks:
      - default

volumes:
  postgres-data:
    name: postgres_data_volume
