services:
  backend:
    image: app_tracker_back_dev_cont:python-3.12-alpine
    container_name: app_tracker_backend_dev
    build:
      target: dev_container
    volumes:
      - ./:/code

  frontend:
    image: app_tracker_front_dev_cont:node-23-alpine3.19
    container_name: app_tracker_frontend_dev
    volumes:
      - ./:/code
    build:
      target: dev_development
    ports:
      - 5173:5173
    environment:
      - NODE_ENV=development
    command: /bin/sh -c "while sleep 1000; do :; done"
